chore(fixes merge package security issue): fixes merge package securi…
freshworks/crayons pull request #198
Opened 2021-05-27 08:18 UTC by shravan-balasubramanian

…ty issue

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] My commits have standard messages as mentioned in [Contributing Guidelines](./../blob/next/CONTRIBUTING.md)
 
## How Has This Been Tested?

2021-05-27 09:32 UTC, asifahmedfw requested changes

2021-05-27 09:32 UTC, asifahmedfw commented on package.json
> +    "commitizen": "4.2.4",
```suggestion
    "commitizen": "^4.2.4",
```
Any problem with this?

2021-05-29 19:58 UTC, shravan-balasubramanian commented
@asifahmedfw There are changes in package-lock file
Its mostly because of the change from node version 10 to 12
The lockfile version changed from 1 -> 2

FYI, I just ran `npm install` to update the package-lock. 

Should we check if it breaks anything? `npm run local` worked fine and there weren't any problems with it

2021-05-31 04:11 UTC, asifahmedfw approved these changes

2021-05-31 04:17 UTC, merged