Fw-Visual-Regression Crayons WC
freshworks/crayons pull request #430
Opened 2022-02-21 08:15 UTC by detiwari003

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My commits have standard messages as mentioned in [Contributing Guidelines](./../blob/next/CONTRIBUTING.md)
 
## How Has This Been Tested?

2022-02-21 10:19 UTC, parsuram-vijaysankar requested changes
- Better you base your branch on the latest conary and raise a new PR, lots of changes seem to be there that might be old. 
- The title of the PR should be semantically named, check contribution guideline. 
- Remove the Reddit references.
- We should not be committing the Report and base Screenshots! 
    - Add a gitignore so that future developers don’t commit these files.
- Able to see tests only for Dropdown and Data-table, where are the tests for Select dropdown and other components?
- Let’s remove the Clone TestDatePicker!

2022-02-24 03:30 UTC, arvindanta requested changes

2022-02-24 03:30 UTC, arvindanta commented on package.json
> +    "visual-test": "start-server-and-test 'npm run storybook:test' 9001 'npm run exe-visual-test' ",
can you please order the scripts in alphabetical order ?

2022-02-24 03:30 UTC, arvindanta commented on package.json
> +    "lit": "^2.1.4",
do we need `lit` as dev dependency ?

2022-02-24 03:30 UTC, arvindanta commented on packages/crayons-core/src/components/crayons-visual-regression-tests/readme.md
> +| Property | Attribute | Description     | Type     | Default     |
Where are these properties being used ?. Can you re generate this readme file ?

2022-03-22 04:20 UTC, closed without merging