docs(fw-form): update fw-form documentation
freshworks/crayons pull request #718
Opened 2022-11-08 13:45 UTC by srivalli-sivaramasankaran

added example for using form inside an accordian

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My commits have standard messages as mentioned in [Contributing Guidelines](./../blob/next/CONTRIBUTING.md)
 
## How Has This Been Tested?

2022-11-08 14:20 UTC, arvindanta requested changes

2022-11-09 04:54 UTC, srivalli-sivaramasankaran commented on packages/crayons-core/src/components/form/readme.md
> +            <FwButton color="secondary" style="display: block; margin-bottom:10px;" onClick={handleFormSubmit}>Submit</FwButton>
fixed

2022-11-09 06:12 UTC, arvindanta requested changes

2022-11-09 06:12 UTC, arvindanta commented on packages/crayons-core/src/components/form/readme.md
> +            <FwButton color="secondary" style={{"display: "block", "margin-bottom" : "10px"}} onClick={handleFormSubmit}>Submit</FwButton>
pls change it to marginBottom: "10px"

2022-11-09 08:45 UTC, arvindanta requested changes

2022-11-09 08:45 UTC, arvindanta commented on packages/crayons-core/src/components/form/readme.md
> +            <FwButton style={{"display: "block"}} onClick={handleFormReset}>Reset</FwButton>
pls remove " before display.

2022-11-09 11:16 UTC, arvindanta approved these changes

2022-11-10 04:38 UTC, merged