fix(date-picker): fix min/max year restriction issue
freshworks/crayons pull request #786
Opened 2023-01-31 14:05 UTC by srivalli-sivaramasankaran

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My commits have standard messages as mentioned in [Contributing Guidelines](./../blob/next/CONTRIBUTING.md)
 
## How Has This Been Tested?

2023-01-31 14:50 UTC, arvindanta requested changes

2023-01-31 14:50 UTC, arvindanta commented on packages/crayons-core/src/components/datepicker/datepicker.tsx
> +      date.setMonth(this.month, 1);
where do we use this `date` variable ?

2023-02-01 04:56 UTC, srivalli-sivaramasankaran commented on packages/crayons-core/src/components/datepicker/datepicker.tsx
> +      date.setMonth(this.month, 1);
Removed.

2023-02-01 08:46 UTC, arvindanta approved these changes

2023-02-01 09:28 UTC, merged