feat(form): Support hide and disable form fields dynamically
freshworks/crayons pull request #860
Opened 2023-05-25 09:59 UTC by Prabhu-Kathiresan

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My commits have standard messages as mentioned in [Contributing Guidelines](./../blob/next/CONTRIBUTING.md)
 
## How Has This Been Tested?

2023-05-30 06:33 UTC, arvindanta requested changes

2023-05-30 06:33 UTC, arvindanta commented on packages/crayons-core/src/components/form/form.tsx
> +    negate = false
Can you name this variable better ?. What does this do?

2023-05-30 06:33 UTC, arvindanta commented on packages/crayons-core/src/components/form/form.tsx
> +  @Prop({ mutable: true }) removeElementFromDomOnHide = false;
Let's not have this as part of the main set of props. Let the method alone take this as argument.

2023-05-30 06:33 UTC, arvindanta commented on packages/crayons-core/src/components/form/form.tsx
> +            let isModified = Boolean(fieldsObj[f.name]);
Can you name this variable better?. What does `isModified` mean?

2023-05-30 06:33 UTC, arvindanta commented on packages/crayons-core/src/components/form/form.tsx
>                  this.shouldRenderFormControl(field) && (
You can use shouldRenderFormControl method to filter the fields instead of `_getVisibleFields` . U can add this logic inside that method

2023-05-30 10:31 UTC, kaushal-freshworks commented on packages/crayons-core/src/components/form/form.tsx
> +  async setHiddenFields(
This is not needed. Can support only hidden fields.

2023-05-30 10:33 UTC, arvindanta commented on packages/crayons-core/src/components/form/form.tsx
> +  @Prop({ mutable: true }) removeElementFromDomOnHide = false;
As discussed, lets only support hidden fields with `display:none`.

2023-05-30 13:51 UTC, arvindanta requested changes

2023-05-30 13:51 UTC, arvindanta commented on packages/crayons-core/src/components/form/form.tsx
> +    const editableFields = Object.keys(disabledFields).reduce(
You can remove this logic from here and add a check in `_handleFieldModifier` to check if the key is `editable` and negate it.

2023-05-31 00:48 UTC, arvindanta approved these changes

2023-05-31 00:48 UTC, arvindanta commented
LGTM

2023-06-05 10:12 UTC, merged