[Feature]: Adds basic properties to support dependent properties for conveFC-114226
freshworks/crayons pull request #896
Opened 2023-10-06 13:46 UTC by prasanna-vijayan

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [ ] My commits have standard messages as mentioned in [Contributing Guidelines](./../blob/next/CONTRIBUTING.md)
 
## How Has This Been Tested?

2023-10-18 02:47 UTC, sangeet-fw requested changes

2023-10-18 02:47 UTC, sangeet-fw commented on packages/crayons-extended/custom-objects/src/components/form-builder/assets/form-builder-preset.json
> +        {
Are these the default values? Do we need them?

2023-10-18 02:47 UTC, sangeet-fw commented on packages/crayons-extended/custom-objects/src/components/form-builder/assets/form-mapper.json
> +      "DEPENDENT_FIELD": { "count": 10, "message": "maximumLimits.fields" }
is the max limit for dependent fields = 10 validated?

2023-10-18 02:47 UTC, sangeet-fw commented on packages/crayons-extended/custom-objects/src/components/form-builder/components/field-editor.tsx
> +  private renderDependentDropdown(boolDisableDropdowns) {
Are we supporting only dropdowns for the dependent fields ?

2023-10-18 02:47 UTC, sangeet-fw commented on packages/crayons-extended/custom-objects/src/components/form-builder/components/field-editor.tsx
> +        ref={(el) => (this.dictInteractiveElements['choices'] = el)}
Can we change the ref name to "dependent_dropdown" or something instead of "choices" here pls

2023-10-18 02:47 UTC, sangeet-fw commented on packages/crayons-extended/custom-objects/src/index.html
> +            "id": "888c6dad-30b2-4030-b070-a704428609fe",
Can we not commit huge changes in index.html - This file is just for local testing. We can avoid commits in this file

2023-11-10 06:54 UTC, prasanna-vijayan commented
Deleting this branch as most of the changes are populated in feat/dependent-field

2023-11-10 06:54 UTC, closed without merging